name: warmd
description: Wanna save the earth?

version: 1.0.11+16

environment:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  provider: ^4.1.3
  flare_flutter: ^2.0.3
  shared_preferences: ^0.5.7+3
  pie_chart: ^3.1.1
  url_launcher: ^5.4.11
  smart_text_view: ^0.1.0
  share: ^0.6.4+3
  cupertino_icons: ^0.1.3
  easy_localization: ^2.3.2
  gradient_text: ^1.0.2
  rive: ^0.0.1+2
  nima: ^1.0.5

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: WarmdIcons
      fonts:
        - asset: fonts/WarmdIcons.ttf
